name: Deploy to Hugging Face

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to HF
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: ${{ secrets.HF_REPO }}
          personal_token: ${{ secrets.HF_TOKEN }}
          publish_dir: ./
          publish_branch: main
          user_name: github-actions
          user_email: github-actions@github.com
